// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/parse": {
            "post": {
                "description": "Parse swagger to doc and python",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "service"
                ],
                "summary": "Parse swagger to doc and python",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Provider name",
                        "name": "provider",
                        "in": "query",
                        "required": true
                    },
                    {
                        "description": "Request",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/http.ParseRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successfully generated python",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Error occurred",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "Error occurred",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Error occurred",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "503": {
                        "description": "Error occurred",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/parse/body": {
            "post": {
                "description": "ParseFromBody swagger to doc and python",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "service"
                ],
                "summary": "ParseFromBody swagger to doc and python",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Provider name",
                        "name": "provider",
                        "in": "query",
                        "required": true
                    },
                    {
                        "description": "Input text data",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successfully generated python",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Error occurred",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "Error occurred",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Error occurred",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "503": {
                        "description": "Error occurred",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/ping": {
            "get": {
                "description": "Ping",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "service"
                ],
                "summary": "Ping",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/responses.PingResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "null"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "null"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "null"
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "type": "null"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "http.ParseRequest": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "string"
                }
            }
        },
        "responses.PingResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "ok": {
                    "type": "boolean"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "generator-inno.poezd.xyz",
	BasePath:         "/api",
	Schemes:          []string{},
	Title:            "API",
	Description:      "API",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
