basePath: /api
definitions:
  responses.PingResponse:
    properties:
      message:
        type: string
      ok:
        type: boolean
    type: object
host: localhost:8000
info:
  contact: {}
  description: API
  title: API
  version: "1.0"
paths:
  /ping:
    get:
      consumes:
      - application/json
      description: Ping
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/responses.PingResponse'
        "400":
          description: Bad Request
          schema:
            type: "null"
        "401":
          description: Unauthorized
          schema:
            type: "null"
        "500":
          description: Internal Server Error
          schema:
            type: "null"
        "503":
          description: Service Unavailable
          schema:
            type: "null"
      summary: Ping
      tags:
      - service
  /python:
    post:
      consumes:
      - text/plain
      description: Generate python
      parameters:
      - description: Input text data
        in: body
        name: data
        required: true
        schema:
          type: string
      produces:
      - text/plain
      responses:
        "200":
          description: Successfully generated python
          schema:
            type: string
        "400":
          description: Error occurred
          schema:
            type: string
        "401":
          description: Error occurred
          schema:
            type: string
        "500":
          description: Error occurred
          schema:
            type: string
        "503":
          description: Error occurred
          schema:
            type: string
      summary: Generate python
      tags:
      - service
swagger: "2.0"
